### ISSUE TITLE
Tu primer API con GraphQL

### ISSUE THREAD

**Issue by jfresco** [workshopsjs/workshops#4]
### Título
Tu primer API con GraphQL

### Descripción
¿GraphQL te parece una buena idea para tu organización pero pensás que reemplazar todas tus APIs es una tarea titánica? No tiene por qué serlo.

En este workshop vamos a aprender a levantar un servidor GraphQL en pocos minutos, crear un esquema de datos y utilizarlo para _wrappear_ tus APIs de forma iterativa e incremental.

De este workshop te vas a ir sabiendo crear un esquema de datos complejo, obtener datos de distintas fuentes, utilizar los resolvers para paralelizar la búsqueda de datos y hacer batching y caching con `dataloader`.

Al final, haremos un cliente en React que consuma nuestra nuestra API.

### Requisitos
Tener instalado:
- Node >= 7 y npm >=5
- Un editor de texto (Atom, Sublime Text, VS Code, etc.)
- Un navegador moderno (Chrome, Firefox)

Además, los participantes deberán tener:
- Conocimiento de JavaScript (especialmente Promises y funciones asincrónicas)
- Conocimiento de cómo funcionan las aplicaciones Web (protocolo HTTP, AJAX, etc.)
- Alguna noción de React puede ser útil pero no es obligatorio.

### Sobre el orador
**Bio** Hago cosas con JavaScript en [Restorando](http://engineering.restorando.com/)
**Foto** https://pbs.twimg.com/profile_images/667692058883301377/S5SBkFeV_400x400.png
**Twitter:** jfresco82

### Recursos
**Slides de la presentación:** en preparación
**Repositorio de la workshop:** en preparación

#### Tenes el workshop preparado?
Está en preparación.

#### En qué mes lo podrías dar?
15 de julio.

**Comment by Villanuevand** [comment]
¡Que buena bio! 😎
